### ISSUE TITLE
App detection / launch fails after proper installation

### ISSUE THREAD

**Issue by wilcollins** [imsardine/winappdriver#12]
![image](https://cloud.githubusercontent.com/assets/1123609/8834593/eb532fd4-3069-11e5-8cce-7c458052986b.png)

The driver appears to download and install the app (based on the logs + it is installed on my machine and I can launch the app), but then the driver fails to launch the app saying that it is not installed yet

UPDATE:

With `v0.2.1` I get the [activation error](https://github.com/imsardine/winappdriver/issues/12#issuecomment-126015721) after a successful installation:

```
2015-11-18 15:52:31.089 [Information] WinAppDriver: Activate the store app; current working directory = [C:\WINDOWS\SysWOW64], AppUserModelID = [a02b50fe-bb55-4be5-8bd9-6c2f93cef175_vr9ykqv283qqw!App].
2015-11-18 15:52:31.111 [Error] WinAppDriver: Error occurred.
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WinAppDriver.Modern.StoreApp.Activate() in z:\work\winappdriver\src\WinAppDriver\Modern\StoreApp.cs:line 128
   at WinAppDriver.Handlers.NewSessionHandler.Handle(Dictionary`2 urlParams, String body, ISession& session) in z:\work\winappdriver\src\WinAppDriver\Handlers\NewSessionHandler.cs:line 159
   at WinAppDriver.RequestManager.Handle(String method, String path, String body, ISession& session) in z:\work\winappdriver\src\WinAppDriver\RequestManager.cs:line 48
   at WinAppDriver.Server.HandleRequest(HttpListenerRequest request, HttpListenerResponse response) in z:\work\winappdriver\src\WinAppDriver\Server.cs:line 47
2015-11-18 15:52:31.141 [Verbose] WinAppDriver: Response (Status: BadRequest, ContentType: text/plain):
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnost
```

**Comment by wilcollins** [comment]
Any idea why the app detection fails after installation?

**Comment by wilcollins** [comment]
@imsardine Any idea why the app detection fails after installation?

**Comment by imsardine** [comment]
@wilcollins I could not reproduce the error using revision 2146557 (v0.1). The error indicates that the package name `WorkTaskManagement` could not be found in the list of installed apps.

I'm afraid that the package name you provided is not correct, so could you help to confirm it by querying install apps manually with the help of PowerShell cmdlet `Get-AppxPackage`. For example:

```
PS C:\> foreach ($app in Get-AppxPackage) { $app.Name }
Microsoft.VCLibs.120.00
Microsoft.VCLibs.120.00
...
winstore
Facebook.Facebook
```

Where you can find the package name of FB store app is `Facebook.Facebook`

**Comment by wilcollins** [comment]
It is not displayed in the list of app package name (and I'm not sure what package the hashed values correspond to)
![image](https://cloud.githubusercontent.com/assets/1123609/8963409/e35989c0-35d4-11e5-8b54-c25eeddda2fe.png)

 but it is installed?
![image](https://cloud.githubusercontent.com/assets/1123609/8963317/5fca7a4c-35d4-11e5-80d2-ec25b37fc74c.png)

**Comment by imsardine** [comment]
@wilcollins I think one of the hash value (`89f2017f-...` or `b7cd92eb-...`) is the package name of your app WorkTaskManagement.

**Comment by wilcollins** [comment]
@imsardine one of the hashed values is the WorkTaskManagement app:
![image](https://cloud.githubusercontent.com/assets/1123609/8963843/097a999e-35d7-11e5-9ff1-737508362748.png)

any idea how to preserve the app package name?

**Comment by wilcollins** [comment]
@imsardine it does not make sense, nor does it work, to pass the hashed value as the package name:
![image](https://cloud.githubusercontent.com/assets/1123609/8963896/5bf5dce2-35d7-11e5-91d1-72d780cdced8.png)

**Comment by imsardine** [comment]
@wilcollins You can declare the package name in the package manifest, for example:

``` xml
<Identity Name="IBM.WorkTaskManagement" .../>
```

For more details, please consult [Windows 8.1 Store apps: Contents of the package manifest](https://msdn.microsoft.com/en-us/library/hh924767.aspx).

**Comment by wilcollins** [comment]
@imsardine OK that looks like it should help -- I was just using a distributed app so I will recompile and retry

**Comment by imsardine** [comment]
@wilcollins You can check out the latest release [v0.2](https://github.com/imsardine/winappdriver/releases/tag/v0.2), and kindly let me know if it works for you.

**Comment by imsardine** [comment]
@wilcollins The latest error you [reported](https://github.com/imsardine/winappdriver/issues/12#issuecomment-126015721) is the same to the error reported in #17. Please check out [v0.2.1](https://github.com/imsardine/winappdriver/releases/tag/v0.2.1) and try it out.

**Comment by wilcollins** [comment]
With ``v0.2.1`` I get a different, but similar error after installation:

````
2015-11-18 15:52:31.089 [Information] WinAppDriver: Activate the store app; current working directory = [C:\WINDOWS\SysWOW64], AppUserModelID = [a02b50fe-bb55-4be5-8bd9-6c2f93cef175_vr9ykqv283qqw!App].
2015-11-18 15:52:31.111 [Error] WinAppDriver: Error occurred.
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WinAppDriver.Modern.StoreApp.Activate() in z:\work\winappdriver\src\WinAppDriver\Modern\StoreApp.cs:line 128
   at WinAppDriver.Handlers.NewSessionHandler.Handle(Dictionary`2 urlParams, String body, ISession& session) in z:\work\winappdriver\src\WinAppDriver\Handlers\NewSessionHandler.cs:line 159
   at WinAppDriver.RequestManager.Handle(String method, String path, String body, ISession& session) in z:\work\winappdriver\src\WinAppDriver\RequestManager.cs:line 48
   at WinAppDriver.Server.HandleRequest(HttpListenerRequest request, HttpListenerResponse response) in z:\work\winappdriver\src\WinAppDriver\Server.cs:line 47
2015-11-18 15:52:31.141 [Verbose] WinAppDriver: Response (Status: BadRequest, ContentType: text/plain):
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnost
````
