### ISSUE TITLE
Selenium with Java :: Application never starting 

### ISSUE THREAD

**Issue by sampadrout** [imsardine/winappdriver#25]
Here is the java code:
package org.tradesktop.com;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.By;
import org.openqa.selenium.Platform;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class deskCalc {
	public static void main(String[] args) throws MalformedURLException, InterruptedException {
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setPlatform(Platform.WINDOWS);
		caps.setCapability(, value);
	    WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444/wd/hub"), caps);
	    driver.get("C:\\Windows\\System32\\calc.exe");
	    driver.quit();
	}
}
When i am running it, the calculator app is never opening up. Here is the server log:
2015-10-22 12:56:16.539 [Information] WinAppDriver: platform = WINDOWS (System.String)
2015-10-22 12:56:16.539 [Information] WinAppDriver: App 'Windows (Desktop)' is already installed, but the installation package is not provided. Reset: Fast
2015-10-22 12:56:16.539 [Verbose] WinAppDriver: Response (Status: OK, ContentType: application/json):{"sessionId":"0c2a17e9-9fd3-430d-a0ca-50759081ec94","status":0,"value"{"platformName":"Windows","appID":null,"packageName":null,"app":null,"appChecksum":null,"checkInstalledCommand":null,"installComm
2015-10-22 12:56:16.585 [Verbose] WinAppDriver: Request: POST /wd/hub/session/0c2a17e9-9fd3-430d-a0ca-50759081ec94/url{"url":"C:\\Windows\\System32\\calc.exe"}
2015-10-22 12:56:16.585 [Verbose] WinAppDriver: Response (Status: OK, ContentType: application/json):{"sessionId":null,"status":0,"value":null}
2015-10-22 12:56:18.601 [Verbose] WinAppDriver: Request: DELETE /wd/hub/session/0c2a17e9-9fd3-430d-a0ca-50759081ec94

2015-10-22 12:56:18.601 [Verbose] WinAppDriver: A corresponding endpoint found:WinAppDriver.Handlers.DeleteSessionHandler
2015-10-22 12:56:18.601 [Verbose] WinAppDriver: Response (Status: OK, ContentType: application/json):{"sessionId":"0c2a17e9-9fd3-430d-a0ca-50759081ec94","status":0,"value":null}

Need your help on this.

**Comment by wilcollins** [comment]
Also seeing ``System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified`` on #12 

````
2015-11-18 15:52:31.089 [Information] WinAppDriver: Activate the store app; current working directory = [C:\WINDOWS\SysWOW64], AppUserModelID = [a02b50fe-bb55-4be5-8bd9-6c2f93cef175_vr9ykqv283qqw!App].
2015-11-18 15:52:31.111 [Error] WinAppDriver: Error occurred.
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WinAppDriver.Modern.StoreApp.Activate() in z:\work\winappdriver\src\WinAppDriver\Modern\StoreApp.cs:line 128
   at WinAppDriver.Handlers.NewSessionHandler.Handle(Dictionary`2 urlParams, String body, ISession& session) in z:\work\winappdriver\src\WinAppDriver\Handlers\NewSessionHandler.cs:line 159
   at WinAppDriver.RequestManager.Handle(String method, String path, String body, ISession& session) in z:\work\winappdriver\src\WinAppDriver\RequestManager.cs:line 48
   at WinAppDriver.Server.HandleRequest(HttpListenerRequest request, HttpListenerResponse response) in z:\work\winappdriver\src\WinAppDriver\Server.cs:line 47
2015-11-18 15:52:31.141 [Verbose] WinAppDriver: Response (Status: BadRequest, ContentType: text/plain):
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnost
````
